### ISSUE TITLE
Component should update state after props changing

### ISSUE THREAD

**Issue by maximgatilin** [tsmith123/react-pluralize#1]
Now I'm using this lib for my project and find issue, that after props changing component does not update state. So component should execute `pluralize` function on componentWillReceiveProps hook

**Comment by tsmith123** [comment]
Thanks for this. Will take a look now.

**Comment by tsmith123** [comment]
This should now be fixed plus I've optimized the package quite a bit. Changed to version 1.1.0.

I'll close for now but let me know how you get on.

**Comment by maximgatilin** [comment]
Yeah, it works, thank you!
