### ISSUE TITLE
Appending the count

### ISSUE THREAD

**Issue by char0n** [tsmith123/react-pluralize#2]
Would be great if by default the component will not append the count to he pluralized noun. Or if we would control the append behavior with additional prop. In the current state it is impossible to use the library if you want to display the count as badge for example.

Would be great if the component was using https://www.npmjs.com/package/pluralize under the hood and make react component that wrap the lib. Are you down for that ?

**Comment by tsmith123** [comment]
I like the first suggestion of an optional count via a prop. I will look to implement this in the next few days. Not sure I really want to go with using another package though in the interest of keeping this one small.

**Comment by char0n** [comment]
> I like the first suggestion of an optional count via a prop. I will look to implement this in the next few days. 

Glad to hear that. I suspect it will increase the download count a bit ;]

> Not sure I really want to go with using another package though in the interest of keeping this one small.

What about making a compromise and making [pluralize](https://github.com/blakeembrey/pluralize)  [optional dependency](https://docs.npmjs.com/files/package.json#optionaldependencies)  ? If it's there it will be used under the hood. If not, current behavior will be fallback. In that way this component can be used even for user input and other use-cases (not just static string prop). Please think about that. I can issue a PR for that.

**Comment by tsmith123** [comment]
I've added the functionality for the optional count. Give it a try and see if it meets your needs.

I'm not going to attempt the optional dependency but feel free to issue a pull request and I will take a look.

**Comment by char0n** [comment]
> I've added the functionality for the optional count. Give it a try and see if it meets your needs.
cool, looks good

> I'm not going to attempt the optional dependency but feel free to issue a pull request and I will take a look.
Will issue a PR and we'll see how it goes from there
