### ISSUE TITLE
className: PropsTypes

### ISSUE THREAD

**Issue by fcallejon** [tsmith123/react-pluralize#6]
Hi, 

is the issue from [Fix error `PropsTypes` is not defined caused by typo](https://github.com/tsmith123/react-pluralize/commit/c43332d1b1199da0082a0a39448309193d2f1225) fixed in the npm version?

The bundle file still have this issue but not index.js.
Even [here](https://npm.runkit.com/react-pluralize) it's failing.

**Comment by tsmith123** [comment]
Can you check now for me using latest version (1.2.3)

**Comment by fcallejon** [comment]
It's working.
Thanks!!
