### ISSUE TITLE
Improper plural for some nouns

### ISSUE THREAD

**Issue by lululombard** [tsmith123/react-pluralize#8]
Hi,

In some cases plural is wrong.

1 berry => 2 berrys
1 search => 2 searchs

I was hopping this plugin would not break grammar and respect plural rules as defined here: https://en.oxforddictionaries.com/spelling/plurals-of-nouns

I'm even surprised that this plugin has 2k+ downloads per week in its current state.

**Comment by tsmith123** [comment]
Can you show me how you are using this please? This package isn't designed to work out the correct plural for you. You must provide the plural form too.

**Comment by lululombard** [comment]
Oh yes sorry, I thought it would process it for me, just like https://github.com/blakeembrey/pluralize
